services:
  mysql:
    image: mysql:latest
    container_name: mysql-inventory
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dostoevsky2324
      MYSQL_DATABASE: inventory_service
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql